### ISSUE TITLE
Delayed suggestions & unwanted suggestions

### ISSUE THREAD

**Issue by markonm** [prabirshrestha/asyncomplete-buffer.vim#1]
Suggestions only appear after 4 seconds. Deleted keyword are still shown as suggestions.
![b](https://user-images.githubusercontent.com/16160229/27666527-a4ef235c-5c74-11e7-9470-396adcc2083d.gif)

If I change `updatetime` to 1, keywords are shown immediately but suggestions are created for every typed letter.
![bb](https://user-images.githubusercontent.com/16160229/27666528-a4f0dddc-5c74-11e7-8afc-960b7ad42aed.gif)

**Comment by mlwarner** [comment]
Hey @xtal8 I am taking a look at this.

an updatetime=1 would fire the cursorhold event every 1ms which seems a bit overkill here.
http://vimhelp.appspot.com/options.txt.html#%27updatetime%27

I don't think the behavior of the CursorHold event is the problem here. It seems to me like we have 2 other issues:

1. There is no cache invalidating. After we cache these words we never remove them.

2. While actively working(without saving), the only event we have that triggers is TextChangedI. From the description at http://vimhelp.appspot.com/autocmd.txt.html#TextChangedI it seems like this would be sufficient, but maybe there are other events which would work here.

**Comment by jsit** [comment]
This is because the `TextChangedI` causes the buffer source to refresh _waaayyyy_ too often. After #4 is merged, you can override the events in your source registration in `.vimrc` with something like this:

```vim
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
	\ 'name': 'buffer',
	\ 'whitelist': ['*'],
	\ 'blacklist': ['go'],
	\ 'events': ['TextChanged','InsertLeave','BufWinEnter','BufWritePost'],
	\ 'completor': function('asyncomplete#sources#buffer#completor'),
	\ }))
```

#2 could be solved by this, as well.

**Comment by jsit** [comment]
> There is no cache invalidating. After we cache these words we never remove them.

This also means that asyncomplete.vim pulls matches from _every buffer you've opened_ in the current Vim session, rather than just the active buffer.
